# Generated by Django 3.2.7 on 2022-03-07 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idAdmin', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/admins/')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('idPartner', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to='images/partenaire/')),
            ],
        ),
        migrations.CreateModel(
            name='VideoEcran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.BooleanField(default=False)),
                ('video', models.CharField(max_length=2000)),
                ('temps', models.CharField(max_length=50)),
                ('index', models.IntegerField(default=0)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('idVideo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('categorie', models.CharField(max_length=50)),
                ('vd', models.FileField(upload_to='videos/')),
                ('minAge', models.IntegerField()),
                ('maxAge', models.IntegerField()),
                ('homme', models.BooleanField()),
                ('femme', models.BooleanField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('idPlaylist', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('libelle', models.CharField(max_length=50)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.admin')),
                ('video', models.ManyToManyField(to='service.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Ecran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEcran', models.CharField(max_length=50)),
                ('idDevice', models.CharField(default='', max_length=50)),
                ('nameDevice', models.CharField(default='', max_length=30)),
                ('timeOpen', models.DateTimeField(blank=True, default='18-05-2016 15:37:36')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.partner')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.partner'),
        ),
    ]
