# Generated by Django 3.2.7 on 2022-03-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecran',
            name='idDevice',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ecran',
            name='nameDevice',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ecran',
            name='timeOpen',
            field=models.DateTimeField(blank=True),
        ),
    ]
